export enum Skill {
    PYTHON, JAVA, NODEJS, REACTJS, ANGULAR, AWS, DATAANALYSIS, ANSYS, SOLIDWORKS, JUNIT, MOCKITO, SPRING,
    SPRINGBOOT, AUTOCAD, CATIA, CPP, C, GIT, MYSQL, KUBERNATES, DOTNET, JAVASCRIPT, CLOUDCOMPUTING, AZURE, GCP,
    ML, AI, SMM, SEO, SEM, CYBERSECURITY, ADWORDS, LINUX, MONGODB, UX, UI, SQLITE, POSTGRESQL, POSTMAN, HTML, CSS,
    SELENIUM, DEVOPS, GOOGLING, MSOFFICE, LIBREOFFICE, TROUBLESHOOTING, NETWORKING, WORDPRESS, FLASK, HIBERNATE, PHOTOSHOP, APACHE, PERL, XML, SWIFT, BLOCKCHAIN,
    PHP
}
